# Generated by Django 5.1.6 on 2025-02-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
        ('User', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
