# Generated by Django 5.1.6 on 2025-03-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0005_remove_transaction_order_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
