# Generated by Django 5.1.6 on 2025-03-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trading', '0006_transaction_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='transfer_id',
        ),
    ]
